"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Tx = { _id:string; type:string; amount:number; source?:string; status:string; userId?:{email?:string;name?:string}; metadata?:{account?:string;bankName?:string;accountName?:string;netPht?:number;netUsd?:number} };
export default function AdminWithdrawals() {
  const [items,setItems]=useState<Tx[]>([]),[totp,setTotp]=useState(""),[message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/admin/transactions");if(r.ok)setItems(((await r.json()).transactions||[]).filter((x:Tx)=>x.type==="withdrawal"&&x.status==="pending"));else setMessage("Admin access required");}
  async function review(id:string,status:"approved"|"rejected"){const r=await fetch("/api/admin/transactions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,totp})});const d=await r.json();setMessage(r.ok?`Withdrawal ${status}.`:d.error||"Review failed");if(r.ok){setTotp("");load();}}
  useEffect(()=>{load()},[]);
  return <main className="min-h-screen bg-[#100b1f] p-5 text-white md:p-10"><div className="mx-auto max-w-5xl"><Link href="/admin" className="text-sm text-violet-300">← Admin dashboard</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Withdrawal review</h1><p className="text-slate-400">Large payouts require your 6-digit TOTP code.</p></div><input value={totp} onChange={e=>setTotp(e.target.value.replace(/\D/g,"").slice(0,6))} className="field max-w-48" inputMode="numeric" placeholder="TOTP code"/></div>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3">{message}</p>}<div className="mt-6 space-y-3">{items.length===0?<p className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-slate-500">No pending withdrawals.</p>:items.map(tx=><article key={tx._id} className="rounded-2xl border border-white/10 bg-[#211737] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><b>{tx.userId?.email||tx.userId?.name||"Member"}</b><p className="mt-1 text-sm text-slate-300">{Math.abs(tx.amount).toLocaleString()} PHT · {tx.source}</p><p className="text-xs text-slate-500">{tx.metadata?.bankName} {tx.metadata?.accountName} · {tx.metadata?.account}</p></div><div className="flex gap-2"><button onClick={()=>review(tx._id,"rejected")} className="rounded-xl border border-red-400/30 px-4 py-3 text-red-300">Reject & refund</button><button onClick={()=>review(tx._id,"approved")} className="rounded-xl bg-amber-300 px-4 py-3 font-bold text-[#211737]">Approve payout</button></div></div></article>)}</div></div></main>;
}
