const BASE = process.env.ACCESSTRADE_API_URL || "https://api.accesstrade.vn";
type JsonRecord = Record<string, unknown>;
function headers() { const key = process.env.ACCESSTRADE_API_KEY; if (!key) throw new Error("Missing ACCESSTRADE_API_KEY"); return { "Content-Type": "application/json", Authorization: `Token ${key}` }; }
function list(payload: unknown, depth = 0): JsonRecord[] { if (Array.isArray(payload)) return payload as JsonRecord[]; if (!payload || typeof payload !== "object" || depth > 3) return []; const value = payload as JsonRecord; for (const candidate of [value.data, value.campaigns, value.items, value.results]) { const nested = list(candidate, depth + 1); if (nested.length) return nested; } return []; }
async function getPages(path: (page: number) => string, pages = 10) { const responses = await Promise.all(Array.from({ length: pages }, (_, i) => fetch(`${BASE}${path(i + 1)}`, { headers: headers(), next: { revalidate: 300 } }))); const failed = responses.find(r => !r.ok); if (failed) throw new Error(`AccessTrade API failed: ${failed.status}`); return (await Promise.all(responses.map(r => r.json()))).flatMap(list); }
function classify(c: JsonRecord) { const text=[c.name,c.title,c.merchant,c.category,c.sub_category,JSON.stringify(c.description||{})].filter(Boolean).join(" ").toLowerCase(); const referral=/accesstrade\s*referral|access\s*trade\s*referral/.test(text); const cps=/shopee|lazada|tiki|cellphones|aeon|eshop|thương mại điện tử|ecommerce|mua sắm|retail|cps/.test(text); const game=/game|gaming|trò chơi/.test(text); const finance=/bank|ngân hàng|wallet|ví điện tử|momo|vnpay|kbank|mbbank|cake|tnex/.test(text); const loan=/loan|vay|tín dụng|credit|cpl/.test(text); const kind=game?"GAME":loan?"CPL":finance?"CPA":cps?"CPS":"OTHER"; return { referral, kind, fastReward:["CPA","GAME"].includes(kind) }; }
export async function getAccessTradeCampaigns() { const [campaigns,rates]=await Promise.all([getPages(page=>`/v1/campaigns?page=${page}&limit=20&approval=successful`),getPages(page=>`/v1/cashback/campaigns?page=${page}&page_size=20`)]); const unique=[...new Map(campaigns.map(c=>[String(c.id||c.campaign_id||""),c])).values()].filter(c=>c.id||c.campaign_id); const rateMap=new Map(rates.map(r=>[String(r.campaign_id||r.id||""),r])); const blocked=(process.env.ACCESSTRADE_BLOCKED_CAMPAIGNS||"").split(",").map(x=>x.trim()).filter(Boolean); const data=unique.flatMap(c=>{const id=String(c.campaign_id||c.id||"");const policy=classify(c);if(String(c.approval||"").toLowerCase()!=="successful"||Number(c.status??1)!==1||policy.referral||blocked.includes(id)||policy.kind==="CPS")return[];const r=rateMap.get(id)||{};return [{campaign_id:id,name:String(c.name||c.title||c.merchant||"Available offer"),merchant:String(c.merchant||""),logo:c.logo||c.image||c.image_url,url:c.url,description:c.description,category:c.category,campaign_type:policy.kind,max_commission:Number(r.max_commission||c.max_commission||0),min_commission:Number(r.min_commission||c.min_commission||0),commission_type:r.commission_type||c.commission_type,fast_reward:policy.fastReward,incentive_allowed:true}];}); return {data,totalCampaigns:unique.length,excluded:unique.length-data.length,policy:"approved-running-incentive-non-cps"}; }
export async function createAccessTradeLink(campaignId:string,clickId:string,url?:string){const response=await fetch(`${BASE}/v1/product_link/create`,{method:"POST",headers:headers(),body:JSON.stringify({campaign_id:campaignId,urls:url?[url]:undefined,sub1:clickId,utm_source:"pureearn",utm_medium:"offerwall",utm_campaign:campaignId,utm_content:clickId,url_enc:true})});if(!response.ok)throw new Error(`AccessTrade link failed: ${response.status}`);return response.json();}
export async function getAccessTradeTransactions(since:Date,until=new Date()){const query=new URLSearchParams({since:since.toISOString(),until:until.toISOString(),limit:"100",utm_source:"pureearn"});const response=await fetch(`${BASE}/v1/transactions?${query}`,{headers:headers(),cache:"no-store"});if(!response.ok)throw new Error(`AccessTrade transactions failed: ${response.status}`);return list(await response.json());}
