import { NextResponse } from "next/server";
import { getAuthSession } from "@/lib/auth";
import { connectDB } from "@/lib/mongodb";
import Submission from "@/models/Submission";
import User from "@/models/User";
import Minijob from "@/models/Minijob";
import Transaction from "@/models/Transaction";
export async function GET() { const session = await getAuthSession(); if (session?.user?.role !== "admin") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); await connectDB(); return NextResponse.json({ submissions: await Submission.find({ status: "pending" }).populate("userId minijobId").sort({ createdAt: 1 }).lean() }); }
export async function PATCH(request: Request) { const session = await getAuthSession(); if (session?.user?.role !== "admin") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { id, status, reviewNote } = await request.json(); if (!id || !["approved", "rejected"].includes(status)) return NextResponse.json({ error: "Invalid review" }, { status: 400 }); await connectDB(); const submission = await Submission.findOne({ _id: id, status: "pending" }).populate("minijobId"); if (!submission) return NextResponse.json({ error: "Submission already reviewed or not found" }, { status: 404 }); submission.status = status; submission.reviewNote = reviewNote; submission.reviewedBy = session.user.id as never; submission.reviewedAt = new Date(); await submission.save(); if (status === "approved") { const job = submission.minijobId as unknown as { reward?: number; rewardCurrency?: string }; const rawReward = Number(job?.reward || 0); const rewardPht = job?.rewardCurrency === "PHT" ? Math.floor(rawReward) : Math.floor(rawReward * 1000); if (rewardPht > 0) { await User.findByIdAndUpdate(submission.userId, { $inc: { phtBalance: rewardPht } }); await Transaction.create({ userId: submission.userId, type: "earning", currency: "PHT", amount: rewardPht, status: "approved", source: "minijob", reference: `minijob:${submission._id}`, metadata: { submissionId: submission._id } }); } } return NextResponse.json({ submission }); }
